#!/sbin/runscript
# Distributed under the terms of the GNU General Public License v2

depend() {
	use logger
	need net
}

SNMPTRAPD_PIDFILE="${SNMPTRAPD_PIDFILE:-/var/run/snmptrapd.pid}"

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start --quiet --exec /usr/sbin/snmptrapd \
		-- -p ${SNMPTRAPD_PIDFILE} ${SNMPTRAPD_FLAGS}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --quiet --pidfile ${SNMPTRAPD_PIDFILE}
	eend $?
}
