#!/usr/bin/python2
import portage
f=open("/var/tmp/stage-pkgs.txt")
di ={}
for a in f.readlines():
	b = a.split("/")
	key = "/".join(b[4:6])
	di[key] = True
for k in di:
	if portage.catpkgsplit(k) != None:
		print(k)
