#!/usr/bin/python2
import portage
f=open("/var/tmp/stage-pkgs.txt")
di ={}
for a in f.readlines():
	b = a.split("/")
	key = "/".join(b[4:6])
	di[key] = True
for k in di:
	cps = portage.catpkgsplit(k)
	if cps != None:
		print "/".join(portage.catpkgsplit(k)[0:2])
