.\" Copyright (c) 1996 Free Software Foundation, Inc.
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the kernel source directory
.\" $Id: lsmod.8 1.1 Fri, 05 Jan 2001 12:45:19 +1100 kaos $
.\"
.TH LSMOD 8 "26 Dec 1996" Linux "Linux Module Support"
.SH NAME
lsmod \- list loaded modules.
.SH SYNOPSIS
.B lsmod
.SH DESCRIPTION
.B Lsmod
shows information about all loaded modules.
.PP
The format is name, size, use count, list of referring modules.  The
information displayed is identical to that available from /proc/modules.
.SH SEE ALSO
insmod(8), modprobe(8), depmod(8), rmmod(8), ksyms(8), modules(2)
.SH HISTORY
Module support was first conceived by Anonymous
.br
Initial Linux version by Bas Laarhoven <bas@vimec.nl>
.br
Version 0.99.14 by Jon Tombs <jon@gtex02.us.es>
.br
Extended by Bjorn Ekwall <bj0rn@blox.se>
.br
Updated for 2.1.17 by Richard Henderson <rth@tamu.edu>
.br
Updated by Bjorn Ekwall <bj0rn@blox.se> in March 1999
