.\" Copyright (c) 1996 Free Software Foundation, Inc.
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the kernel source directory
.\" $Id: modinfo.8,v 1.1 2001/09/13 21:10:55 jhutz Exp $
.\"
.TH MODINFO 8 "11 Nov 1997" Linux "Linux Module Support"
.SH NAME
modinfo \- display information about a kernel module
.SH SYNOPSIS
.B modinfo
[ options ] <module_file>
.SH DESCRIPTION
The
.B modinfo
utility examines the object file
.I module_file
associated with a kernel module and displays any information that it
can glean.
.SS OPTIONS
.TP
.BR \-a ", " \-\-author
Display the module's author.
.TP
.BR \-d ", " \-\-description
Display the module's description.
.TP
.BR \-n ", " \-\-filename
Display the module's filename.
.TP
.BI \-f format_string ", \-\-format " format_string
Let the user specify an arbitrary format string which can extract
values from the ELF section in
.I module_file
which contains the module information.
Replacements consist of a percent sign followed by a tag name in curly
braces.
A tagname of %{filename} is always supported, even if the module has no
modinfo section.
.TP
.BR \-p ", " \-\-parameters
Display the typed parameters that a module may support.
.TP
.BR \-h ", " \-\-help
Display a small usage screen.
.TP
.BR \-V ", " \-\-version
Display the version of
.BR modinfo .
.SH "SEE ALSO"
.BR insmod "(8), " modprobe "(8), " depmod "(8), " rmmod "(8), "
.BR lsmod "(8), " ksyms "(8), " modules "(2) "
