#!/sbin/runscript
# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	use net
}

start() {
	ebegin "Starting uftpd"
	start-stop-daemon --start --pidfile "${PIDFILE}" --user nobody \
	--exec /usr/sbin/uftpd -- -P "${PIDFILE}" ${UFTPD_OPTS}
	eend ${?}
}

stop() {
	ebegin "Stopping uftpd"
	start-stop-daemon --stop --pidfile "${PIDFILE}" --exec /usr/sbin/uftpd
	eend ${?}
}
