#!/sbin/runscript
# Copyright 2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: /var/cvsroot/gentoo-x86/dev-vcs/subversion/files/svnserve.initd,v 1.1 2010/06/22 18:17:21 arfrever Exp $

depend() {
	need net
}

start() {
	ebegin "Starting svnserve"
	# Ensure that we run from a readable working dir, and that we do not
	# lock filesystems when being run from such a location.
	cd /
	start-stop-daemon --start --quiet --background --make-pidfile \
		--pidfile /var/run/svnserve.pid --exec /usr/bin/svnserve \
		--chuid ${SVNSERVE_USER:-apache}:${SVNSERVE_GROUP:-apache} -- \
		--foreground --daemon ${SVNSERVE_OPTS:---root=/var/svn}
	eend $?
}

stop() {
	ebegin "Stopping svnserve"
	start-stop-daemon --stop --quiet --pidfile /var/run/svnserve.pid
	eend $?
}
