# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.13.02

MODULE_AUTHOR=TJC
inherit perl-module

#S=${WORKDIR}/${P}
DESCRIPTION="Catalyst plugin for CGI::Untaint."

IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~amd64 ~x86"

DEPEND="
	dev-perl/Catalyst-Runtime
	>=dev-perl/CGI-Untaint-1.20
"
